### ISSUE TITLE
Weird lines on terrain

### ISSUE THREAD

**Issue by Aerosoft8** [niels747/Weather_Sim_4#6]
These lines appear on terrain randomly while I zoom
![Screenshot 2022-06-22 000904](https://user-images.githubusercontent.com/105531208/174879228-558f429c-103b-4327-b974-89cd2b6311e2.png)

**Comment by niels747** [comment]
I am aware of it, I will try to fix it.

**Comment by niels747** [comment]
> I like the new update, but the rainfall is too light, almost non-existent, even though the threshold is zero

You can simply increase the growth rates and spawn rate in the precipitation menu.  I am trying to finetune all the parameters to make it as realistic as possible, but I made them all user adjustable so anyone can experiment with it.

**Comment by niels747** [comment]
> These lines appear on terrain randomly while I zoom ![Screenshot 2022-06-22 000904](https://user-images.githubusercontent.com/105531208/174879228-558f429c-103b-4327-b974-89cd2b6311e2.png)

**I fixed it.**
The problem was in realDispShader.vert on line 20: 
`const float Xmult = 100.5;` 
This high multiplier was causing precision issues in the horizontal coordinate, resulting in those ugly vertical lines.
Replaced it by
`const float Xmult = 4.;`   
Now a new problem arose wich is that you can quicly scroll out of the rendered area and see black. 
To fix this I added some code in the camera controlls to make the viewXpos seamlesly jump using modulo.
